/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.portgo.util;

import android.content.Context;
import android.text.TextUtils;

import com.portgo.manager.CallManager;
import com.portgo.manager.PortSipCall;
import com.portgo.manager.SipManager;
import com.portsip.PortSipErrorcode;

import java.util.TimerTask;

public class CallReferTask extends TimerTask{
	final int callReferDelay;
	final String callReferTo;
	final SipManager sipManager;
    CallManager callManager;
	final long sessionId ;
    final Context context;
	public CallReferTask(long sessionID, int delay, String referTo, SipManager handle, CallManager callManager, Context context){
		callReferDelay = delay;
		callReferTo = referTo;
		sipManager = handle;
		this.sessionId = sessionID;
        this.callManager= callManager;
        this.context = context;
	}
	@Override
	public void run() {
		if(!TextUtils.isEmpty(callReferTo)&&callReferDelay>0&&sipManager!=null){

            if(sipManager.portforwardCall(sessionId,callReferTo)== PortSipErrorcode.ECoreErrorNone){
                PortSipCall call= callManager.getCallBySessionId(sessionId);
                if(call!=null) {
                    call.reject(context);
                }
            }
		}

	}

    public boolean timeAvailable(){
        return callReferDelay>0;
    }

    public int getDelayTime(){
        return callReferDelay;
    }
}